param([string]$Date = (Get-Date -Format 'yyyy-MM-dd'))

$root = Get-Location
$log  = Join-Path $root ("logs\engine-{0}.log" -f $Date)
if (-not (Test-Path $log)) { throw "No log for $Date at $log" }

$last = Get-Content $log | Select-Object -Last 1 | ConvertFrom-Json
if (-not $last) { throw "No entries in $log" }

$shiftColor = @{
  grounded   = '#CEEDC7'
  compassion = '#FDE2E4'
  clarity    = '#E2F0F9'
  courage    = '#FFF4CC'
  release    = '#EAEAEA'
}
$bg = $shiftColor[$last.shift]; if (-not $bg) { $bg = '#F7F7F7' }

$chips = ""
if ($last.chakra) {
  $chips = ($last.chakra -split ',' | ForEach-Object { "<span class='chip'>$_</span>" }) -join " "
}

$outDir = Join-Path $root 'cards'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$ts = Get-Date -Format "yyyyMMdd-HHmmss"
$outFile = Join-Path $outDir ("auraflow-card-{0}.html" -f $ts)

@"
<!doctype html>
<meta charset="utf-8">
<title>AuraFlow  Daily Card</title>
<style>
  :root { color-scheme: light; }
  body { font-family: ui-sans-serif, system-ui, Segoe UI, Arial; background:$bg; margin:0; padding:24px; color:#222; }
  .card { background:#fff; border-radius:16px; padding:24px; box-shadow:0 10px 30px rgba(0,0,0,.08); max-width:640px; margin: 0 auto; }
  h1 { margin:0 0 8px 0; font-size:24px; }
  .sub { color:#666; margin-bottom:16px; }
  .row { display:flex; gap:12px; flex-wrap:wrap; margin-bottom:8px; }
  .pill { background:#f3f3f3; border-radius:12px; padding:6px 10px; font-size:14px; }
  .chips { margin-top:8px; }
  .chip { display:inline-block; background:#f6f6f6; border:1px solid #eee; border-radius:999px; padding:4px 10px; margin-right:6px; font-size:12px; }
  .practice { font-size:18px; line-height:1.5; margin-top:16px; }
  .footer { margin-top:18px; font-size:12px; color:#777; }
</style>
<div class="card">
  <h1>Morning State  $($last.shift.Substring(0,1).ToUpper() + $last.shift.Substring(1))</h1>
  <div class="sub">$($last.ts)</div>

  <div class="row">
    <div class="pill">Mood: $($last.mood)</div>
    <div class="pill">Energy: $($last.energy)</div>
    <div class="pill">Focus: $($last.focus)</div>
  </div>

  @(if ($last.note) { "<div class='row'><div class='pill'>Note: $($last.note)</div></div>" })

  <div class="chips">$chips</div>

  <div class="practice">$($last.sample)</div>

  <div class="footer">Generated by AuraFlow (local preview)</div>
</div>
"@ | Set-Content -Path $outFile -Encoding UTF8

Write-Host "Saved card  $outFile"
Start-Process $outFile
